version: '3'

services:
  crypto-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: crypto-analyzer
    environment:
      - NODE_ENV=production
