apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crypto-analyzer.fullname" . }}-nginx-config
  labels:
    {{- include "crypto-analyzer.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen {{ .Values.service.port }};
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
        
        {{- if .Values.nginxConfig.apiProxy.enabled }}
        location /api/coingecko/ {
            proxy_pass {{ .Values.nginxConfig.apiProxy.coingeckoUrl }}/;
            proxy_set_header Host api.coingecko.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_server_name on;
            proxy_redirect off;
            proxy_buffering off;
        }
        {{- end }}
        
        # Enable gzip compression
        gzip on;
        gzip_comp_level 5;
        gzip_min_length 256;
        gzip_proxied any;
        gzip_vary on;
        gzip_types
          application/javascript
          application/json
          application/x-javascript
          text/css
          text/javascript
          text/plain
          text/xml;
    }
